FROM node:20-alpine AS build

WORKDIR /app
COPY package*.json ./
RUN npm install -g @angular/cli firebase-tools && npm install

COPY . .
RUN ng build --configuration production

# At the end, the dist folder will be ready for firebase deploy
