version: "3.8"

services:
  frontend-prod:
    image: fresh-cart-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    volumes:
      - .:/app
    working_dir: /app
    command: >
      sh -c "
      npm install -g firebase-tools &&
      ng build --configuration production &&
      firebase deploy --only hosting
      "
